/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SherlockRouteImport } from './routes/sherlock'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as SandboxRouteImport } from './routes/sandbox'
import { Route as GraphRouteImport } from './routes/graph'
import { Route as ArchiveRouteImport } from './routes/archive'
import { Route as IndexRouteImport } from './routes/index'

const SherlockRoute = SherlockRouteImport.update({
  id: '/sherlock',
  path: '/sherlock',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const SandboxRoute = SandboxRouteImport.update({
  id: '/sandbox',
  path: '/sandbox',
  getParentRoute: () => rootRouteImport,
} as any)
const GraphRoute = GraphRouteImport.update({
  id: '/graph',
  path: '/graph',
  getParentRoute: () => rootRouteImport,
} as any)
const ArchiveRoute = ArchiveRouteImport.update({
  id: '/archive',
  path: '/archive',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/archive': typeof ArchiveRoute
  '/graph': typeof GraphRoute
  '/sandbox': typeof SandboxRoute
  '/settings': typeof SettingsRoute
  '/sherlock': typeof SherlockRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/archive': typeof ArchiveRoute
  '/graph': typeof GraphRoute
  '/sandbox': typeof SandboxRoute
  '/settings': typeof SettingsRoute
  '/sherlock': typeof SherlockRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/archive': typeof ArchiveRoute
  '/graph': typeof GraphRoute
  '/sandbox': typeof SandboxRoute
  '/settings': typeof SettingsRoute
  '/sherlock': typeof SherlockRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    '/' | '/archive' | '/graph' | '/sandbox' | '/settings' | '/sherlock'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/archive' | '/graph' | '/sandbox' | '/settings' | '/sherlock'
  id:
    | '__root__'
    | '/'
    | '/archive'
    | '/graph'
    | '/sandbox'
    | '/settings'
    | '/sherlock'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ArchiveRoute: typeof ArchiveRoute
  GraphRoute: typeof GraphRoute
  SandboxRoute: typeof SandboxRoute
  SettingsRoute: typeof SettingsRoute
  SherlockRoute: typeof SherlockRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sherlock': {
      id: '/sherlock'
      path: '/sherlock'
      fullPath: '/sherlock'
      preLoaderRoute: typeof SherlockRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sandbox': {
      id: '/sandbox'
      path: '/sandbox'
      fullPath: '/sandbox'
      preLoaderRoute: typeof SandboxRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/graph': {
      id: '/graph'
      path: '/graph'
      fullPath: '/graph'
      preLoaderRoute: typeof GraphRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/archive': {
      id: '/archive'
      path: '/archive'
      fullPath: '/archive'
      preLoaderRoute: typeof ArchiveRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ArchiveRoute: ArchiveRoute,
  GraphRoute: GraphRoute,
  SandboxRoute: SandboxRoute,
  SettingsRoute: SettingsRoute,
  SherlockRoute: SherlockRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
